#!/usr/bin/env python3
"""Emit explicit rational weighted-square identities; Lean checks every identity."""
from lean_source import write_lean
from pathlib import Path
import json
from fractions import Fraction as Q
from itertools import permutations, combinations
ROOT=Path(__file__).resolve().parents[1]
def rat(x):
 x=Q(x)
 return str(x.numerator) if x.denominator==1 else f'({x.numerator}/{x.denominator} : ℝ)'
def quad(v,block):
 terms=[]
 for k,(i,j) in zip(v,block):
  if k: terms.append(f'({rat(k)}) * (a {i} * a {j})')
 return ' + '.join(terms) or '0'
def sos(cert):
 result=[]
 for block,E,K in zip(cert['blocks'],cert['E'],cert['K']):
  E=[[Q(x) for x in r] for r in E]; K=[[Q(x) for x in r] for r in K]; n=len(K)
  if len(block)==4 and (all(a//4==b//4 and a!=b for a,b in block) or all(a%4==b%4 and a!=b for a,b in block)):
   assert E==[[Q(-1),Q(-1),Q(-1)],[Q(1),Q(0),Q(0)],[Q(0),Q(1),Q(0)],[Q(0),Q(0),Q(1)]]
   K=[[x-Q(1,1000)*(3 if i==j else -1) for j,x in enumerate(row)] for i,row in enumerate(K)]
  for i in range(n):
   d=K[i][i]; assert d>0
   v=[E[j][i]+sum(K[i][k]/d*E[j][k] for k in range(i+1,n)) for j in range(len(E))]
   result.append((d,v,block))
   for j in range(i+1,n):
    for k in range(j,n):
     K[j][k]-=K[j][i]*K[i][k]/d; K[k][j]=K[j][k]
 return result
def emit(index,cert):
 terms=[]
 for p,w in zip(permutations(range(4)),cert['weights']):
  terms.append(f'({rat(w)}) * ('+' * '.join(f'a {4*i+j}' for i,j in enumerate(p))+')')
 target='(3/32 : ℝ) * ('+' + '.join(f'a {j} ^ 2' for j in range(16))+') ^ 2 - ('+' + '.join(terms)+')'
 defect_terms=[]
 for i,j in combinations(range(4),2):
  for k,l in combinations(range(4),2):
   defect_terms += [f'(a {4*i+k} * a {4*i+l} - a {4*j+k} * a {4*j+l}) ^ 2',
                    f'(a {4*i+k} * a {4*j+k} - a {4*i+l} * a {4*j+l}) ^ 2']
 target+=' - (1/1000 : ℝ) * ('+' + '.join(defect_terms)+')'
 squares=sos(cert)
 rhs=' +\n      '.join(f'{rat(d)} * ({quad(v,b)}) ^ 2' for d,v,b in squares)
 src=f'''import Mathlib.Tactic

namespace FourRow
set_option maxRecDepth 100000
set_option maxHeartbeats 0

/-- Explicit exact rational SOS identity for oriented law {index}. -/
theorem gram{index:03d} (a : Fin 16 → ℝ) :
    0 ≤ {target} := by
  have identity : {target} =
      {rhs} := by ring
  rw [identity]
  positivity
end FourRow
'''
 p=ROOT/'FourRow'/'Grams'/f'G{index:03d}.lean';p.parent.mkdir(exist_ok=True);write_lean(p,src)
 return len(src)
if __name__=='__main__':
 import argparse
 a=argparse.ArgumentParser();a.add_argument('--limit',type=int,default=1);args=a.parse_args()
 certs=json.loads((ROOT/'evidence/certificates.json').read_text())['certificates']
 print('generated bytes',sum(emit(i,c) for i,c in enumerate(certs[:args.limit])))
